# Core site functionality
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "" # the subpath of your site, e.g. /blog
title: "Flyhigh Theme" # the name of your site, e.g. ACME Corp.
header-logo: "" # Will replace site title in the header
tagline: "For those who want more frosted glass in their life..." # Short site description, just a few words
description: "A Jekyll theme for those who want more frosted glass in their life. Developed by Ahhhh-man and monotiller" # Long site description
logo: "/assets/images/branding/default.jpg" # The logo that is served to search engines
keywords: "Jekyll, Theme" # Comma separated keywords about the content of the site
owner: "Ahhhh-man, monotiller" # Who is in charge of this site?
lang: "en-GB" # The language of your site, defaults to en-GB (British English)
embed-theme: "#ffcd05" # The colour that will be displayed in places such as embeds, provide as a hex value
background-image: "assets/images/brand/default.jpg" # Default image from here: https://unsplash.com/photos/1tb5N7Q97Sw

# SEO Tag settings - See here for full instructions: https://github.com/jekyll/jekyll-seo-tag
# Social media
twitter:
  username: github
  card: summary
facebook:
  app_id: 
  publisher: https://facebook.com/github
  admins: 
social:
  links:
    # Styled like this: - https://example.com
webmaster_verifications:

# Additional social media that isn't supported by the SEO above:
github: github # Just your username or user/repo

# Blog options
permalink: ':year/:month/:title.html' # Style of permalinks for blog posts
paginate: 5 # How many posts per page
paginate_path: "blog/page:num/" # How to lay out blog posts

# Collections configuration helps to organise things such as blog posts
collections:
  authors:
    output: true

# Setting up defaults
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Help to extend the site functionality
plugins:
  # Required plugins
  - jekyll-avatar # Allows you to use your GitHub avatar around the site
  - jekyll-sitemap # Generates an XML sitemap for search engines
  - jekyll-feed # Genearates feeds so people can follow your blog content
  - jekyll-seo-tag # Makes it easier to provide search engines with information about your site
  - jekyll-paginate # Allows for groups of content to be split amongst multiple pages

  # User added plugins (put yours here!)